### ISSUE TITLE
Allow smaller (or custom) "smallest weight plate" options

### ISSUE THREAD

**Issue by kpfile** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#17]
The end result I'm interested in is getting the lift weights to round to the nearest 1kg, instead of 2.5kg, so in this case I'd want a 0.5kg option for "smallest weight plate".  Can make all the difference on my poor OHP! :)

I mentioned this on twitter and now i'm here.  Thank again for the app!!

**Comment by JonnyBeeGod** [comment]
Done
