### ISSUE TITLE
Allow setting Kg or Lb individually for accessories

### ISSUE THREAD

**Issue by kpfile** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#18]
It almost seems like this was originally intended, because when you go to select the weight for an accessory exercise, "kg" is there and you can kinda spin it, but there is no "lb" option to switch it to.  

I use KG bar/plates but LB dumbells, so it would be nice to be able to record things correctly.  It isn't a huge deal though, because when I look at my history, I know what type of weight I was using even though it is labeled as KG on a dumbell accessory.  So, this is pretty minor.

**Comment by JonnyBeeGod** [comment]
Ha! Don't know how I missed that, yes that was intended to be implemented and I forgot. This will probably get fixed pretty soon

**Comment by JonnyBeeGod** [comment]
implemented in 1.5.0
