### ISSUE TITLE
When moving from 5 day to 6 day, the graphs lose their numbers

### ISSUE THREAD

**Issue by AaronRustad** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#19]
I just moved from 5 day to 6 day squat and I noticed that the graphs no longer display the weight/numbers.

If I jump back to 5 day, they show up again.

![img_5645](https://user-images.githubusercontent.com/17159/33277811-dd9d8a1e-d356-11e7-995b-8739125e82e5.jpg)

**Comment by JonnyBeeGod** [comment]
This is intended as space for the labels gets more and more sparse when accumulating more data. There is simply not enough space to show the labels any more for each data entry. You can pinch zoom on each graph to show the labels again or you can rotate your phone to landscape to show the combine graph, then you will see the labels again.

**Comment by AaronRustad** [comment]
Right, I see now. It wasn't immediately obvious. Works like a charm.

**Comment by JonnyBeeGod** [comment]
It is indeed not obvious. I think more users will have this problem, some kind of indication or help text would be nice. Thank you for the feedback
