### ISSUE TITLE
Save weight of logged sets

### ISSUE THREAD

**Issue by JonnyBeeGod** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#21]
Changing the unit or the smallest weight plate in the settings can update the weight of already logged sets as well. The weight of logged sets needs to be persisted

**Comment by aaron25mt** [comment]
This also happens if you manually change the TM.

**Comment by JonnyBeeGod** [comment]
@aaron25mt new issue: https://github.com/JonnyBeeGod/nSuns-5-3-1-iOS-issues/issues/29
