### ISSUE TITLE
App doesn’t ask for notifications permissions

### ISSUE THREAD

**Issue by cubetes** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#28]
If iOS settings are cleared, the app doesn’t ask back for the timer’s notification permissions. When selecting the permit notifications for timer option in settings, there are no notification options available.

The only way to do it is reinstalling the app, which deletes all the workout history.

**Comment by JonnyBeeGod** [comment]
Nasty bug 🤨 Fixed

**Comment by JonnyBeeGod** [comment]
Will come in 1.7.0
