### ISSUE TITLE
No labels for progress after 11 cycles

### ISSUE THREAD

**Issue by aaron25mt** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#32]
Not sure if this is by design or not, but I noticed after 11 cycles, the labels disappear for the charts in the Progress tab. In my opinion, there should be at least some labels shown (if not all but I can see why this might not work) so there's a clear view of progression.

Some ideas for which TMs to show on the graph include: last 5 cycles, first cycle + last 5 cycles, every other cycle, every Xth cycle (maybe use 20% steps), etc.

It'd be even better if this was a settings and you could choose how you'd like your progression to be displayed.

**Comment by JonnyBeeGod** [comment]
Yup, it's by design because at some point there are too many labels. Your suggestions are great, I wanted to do something like that before but it required quite some development effort. 

For now, you can always pinch zoom in and see the labels for a specific subset of your graph

**Comment by firedev** [comment]
I would suggest to display only 10 latest cycles with labels in vertical view. 

Also where is says Squat, Bench, Press, Deadlift - add current training max. So it says Bench 225, Press 135 etc.
