### ISSUE TITLE
Tweak Progression Settings

### ISSUE THREAD

**Issue by lateralun** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#36]
Edited by @JonnyBeeGod: 
Introduce a new setting to change the progression scheme of the app. 
It should be a global setting affecting all templates because there is no need to distinguish progression based on the used template. 

Original comment: 

> Have you considered allowing us to change the progression settings based on the number of 1+ reps performed? I find I quickly hit walls if I go up in weight when I only get 2 reps of something and I have dealt with this by subtracting 1 from my actual rep count when I record it in the app. Is it possible to include a way to change the progression formula in the template editor?

**Comment by JonnyBeeGod** [comment]
Yes I considered this. I think it would be valuable to update this globally via settings or even each cycle with a small popup where you could alter the progression for the next cycle.

**Comment by JonnyBeeGod** [comment]
Shipped with 1.10.0
