### ISSUE TITLE
Timer sometimes doesn't show up

### ISSUE THREAD

**Issue by effati** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#51]
I've noticed in the latest update that after finishing a set (any random set), the timer sometimes doesn't automatically show up as it should. Unchecking and rechecking a set doesn't work. And the timer is gone for future sets as well. The only way to get it back is to quit and restart the app. Happens on an average of 1-2 times per workout.

**Comment by JonnyBeeGod** [comment]
While timer functionality is still kind of skewed in some instances (pressing too quickly on new set when closing animation is still in progress. In that case timer does not show up automatically but only the next time a set has been ticked. This is unfortunately kind of hard to fix) this especially bad behavior has been fixed. Thanks for reporting
