### ISSUE TITLE
Copy last week's accessories

### ISSUE THREAD

**Issue by cbonjoc** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#54]
As title - new cycle created possibly copy accessories and weights and reps used with same amount of sets

**Comment by amIevenAcoder** [comment]
If there's one thing I hate about this app, it's this. I don't want to manually add the same accessories each day. It involves me opening another app just to find out which workouts. I might as well just use the other app then but they don't have the progression/math involved.

Please add this feature.

**Comment by jo3p** [comment]
Not sure if I can “vote” for this as well, but if it’s not too hard to code I’d like to request the same thing ❤️❤️

**Comment by khromosone** [comment]
Also requesting the same feature of copyinng and pasting previous cycles to reduce the re-entering of heaps of accessories.

**Comment by JonnyBeeGod** [comment]
Shipped with 1.12.0
