### ISSUE TITLE
Option to show timer overlay after each set

### ISSUE THREAD

**Issue by bcardarella** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#56]
Currently when I record a set the overlay with the full screen timer comes up. But I usually have to change the weights on the bar between sets. So I always find myself swiping the timer down to see the next set or upcoming sets. It would be great if after I recorded a set I could just get the timer in the bottom of the app without the overlay.

**Comment by JonnyBeeGod** [comment]
I think this is a valid suggestion. However it should be configurable because different users might have different preferences. 

Did you know that the weight for your next set is also shown on the timer overlay on the very top? You basically don't have to minimize to see your next weight.

**Comment by JonnyBeeGod** [comment]
Added "Start Timer minimized" option in timer settings.

**Comment by bcardarella** [comment]
sweet!
