### ISSUE TITLE
Progression with failed non-AMRAP sets

### ISSUE THREAD

**Issue by firedev** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#62]
Extracted from https://github.com/JonnyBeeGod/nSuns-5-3-1-iOS-issues/issues/46#issuecomment-416804394

Hi, I am using a 6-day squat with AMRAP increased to 3+ and last week I started a new cycle after a few weeks break where I had to deload OHP to 135. I failed on two monday T2 sets, but it increased OHP this week to 140 anyway. I completed all T1 OHP sets with 3+ AMRAP though.

Is it a bug? are calculations correct? I thought it would increase the lift only if you complete both T1 and T2 sets.

PS. Sorry I can't reopen it.

**Comment by firedev** [comment]
This week I failed 8 reps on OHP T2 again. And it increased it anyway. Is this a bug?

**Comment by firedev** [comment]
I believe I have pinponted the issue. It always adds weight even with failed sets because each cycle is deemed 100% completed. Before I saw 98% completion or something. Now when I look at the log everything is 100% complete. And despite failed sets the weight is increased across the board.

**Comment by JonnyBeeGod** [comment]
As stated here https://github.com/JonnyBeeGod/nSuns-5-3-1-iOS-issues/issues/46#issuecomment-416804394 the app does not take the T2s into account whether it should increase or not. I implemented it intentionally this way because that’s how I understood the spreadsheet info. We should ask the community whether T2s should be taken into account as well for the requirement to hit all sets in order to progress on the lift.

**Comment by firedev** [comment]
Okay then, how do you increase OHP on 4-day program with no dedicated OHP day?

**Comment by JonnyBeeGod** [comment]
For templates with not dedicated Progressions set like the initial 4 day template you will progress with the smallest possible increment which is dependent on your smaller weight plate.

**Comment by firedev** [comment]
I believe this should be a setting at least. I keep failing last Monday sets on both Bench and OHP and it keeps increasing weights. I am worrying this might not end.

**Comment by firedev** [comment]
Know what, maybe you're right. I keep failing 7/8-rep OHP sets on monday, but still adding weight. Guess switching to AMRAP 3+ helped. Guess that should be optinal. And Monday Bench is not a problem anymore.
