### ISSUE TITLE
More templates 

### ISSUE THREAD

**Issue by JonnyBeeGod** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#63]
- 5 day row template  https://docs.google.com/spreadsheets/d/1fr8RYt3YJkmQohk-GCANHJ5TpovevAUcYG3xQgU6Pvw/htmlview
- wife template 

Preferably configurable via web service for OTA updating and adding of new templates

**Comment by Maelink1** [comment]
Hello Jonny,
I second this feature request it would be very helpful.
Also could you make it so that the app can have more than two main lifts. So then people could have multiple exercises following the same progression scheme as the main two. In the edit workout area.
Thanks
