### ISSUE TITLE
Beta testing signup

### ISSUE THREAD

**Issue by JonnyBeeGod** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#65]
Implement a page to let Users signup for beta testing.
Users will be able to supply their email address and will be automatically added to TestFlight for beta testing.

**Comment by firedev** [comment]
Can we sign up from here?

**Comment by JonnyBeeGod** [comment]
Yup, added more info

**Comment by JonnyBeeGod** [comment]
Implemented and currently in beta testing
