### ISSUE TITLE
Add sets in template editor

### ISSUE THREAD

**Issue by firedev** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#66]
I am trying to have more Squatting using Monday Bench Scheme for Saturday Squats as I have described here https://www.reddit.com/r/nSuns/comments/9cgi2s/fixing_6day_squat/

And would also like to increase Saturday Sumo Deadlifts to heavier 8x3

But I can’t seem to find a way to add more sets.

**Comment by JonnyBeeGod** [comment]
You can't change the amount of reps yet. Tbh I'm not sure whether implementing something like this should be done in this app. With this amount of configurability is it still nSuns we're running? You could basically make any program with the template editor. On the other hand why not if this is what user want to do. For deload weeks it could also make sense or after injuries.

**Comment by JonnyBeeGod** [comment]
I wanted to say 'You can't change the amount of sets yet' instead I said 'reps', sorry for the confusion. Your point of altering the amount of reps still stands. Or did you somehow manage to change the amount of sets? :)

**Comment by firedev** [comment]
Nah just fit as many as I could. I was super setting with deadlift as this was too light anyway. Now Saturday is a proper lifting day.
