### ISSUE TITLE
Import / Export Functionality

### ISSUE THREAD

**Issue by JonnyBeeGod** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#68]
**Is your feature request related to a problem? Please describe.**
I want to be able to export all my workout data including custom exercises and the likes and import it again. This would be useful for backup purposes, transferring to a new phone and debugging of user issues.

At the moment the workout data is backuped and restored via the backup mechanisms of iOS. When transferring to a new phone this data is not being transferred. 

Also I have no solution currently in place to reproduce weird behavior of the app from user reports because their phone is in a different state with different workout data. 

**Describe the solution you'd like**
Ideally there should be a way to make a simple export in file format (csv / json) and reimport this data again. Data migration is a problem which drives complexity, so it is sufficient to export / import only for the same app version. CSV would have the additional benefit of being human readable. 

**Describe alternatives you've considered**
there are none

**Comment by pepablock** [comment]
this is something relevant for me atm, because i just bought a new phone. is there a way right now to export my workout data from an old iphone and import them to the new one?
