### ISSUE TITLE
Minimised timer pushes icons off centre in iOS 12.

### ISSUE THREAD

**Issue by dmsean** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#70]
I’ve got an iPhone 7 Plus running iOS 12. Ever since the upgrade to iOS 12, the minimised timer pushes the three bottom icons up and to the left enough that the Manage Cycles icon is half off the screen. The three icons appear to be aligned with the divider between the buttons and the timer. The text for all three icons disappears. 

Great app though.

**Comment by firedev** [comment]
Took the screenshot today:

![image](https://user-images.githubusercontent.com/115612/47787686-b0d15180-dd20-11e8-8cb3-4815fe756799.png)

**Comment by JonnyBeeGod** [comment]
Seems like this happens on the bigger iPhones which I don't have available to reproduce. I tried fixing it, gonna close this issue for now. Please reopen if the issue still persists with the next update which will come in a few days.
