### ISSUE TITLE
Training max no longer updating 

### ISSUE THREAD

**Issue by juicyveal** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#71]
Hi, I'm running the 4-day template, all default settings and progression scheme. No matter how many reps I hit for my progression set, the TM for the next week remains the same. 

Only thing I've changed recently is deloading a few weeks ago and manually decreasing the TM for all my T1 lifts. The progression scheme worked then, but now that I'm surpassing my old TM, the TM is no longer updating. Thank you!

**Comment by JonnyBeeGod** [comment]
Does this still occur?

**Comment by juicyveal** [comment]
Woah, hi! Thanks for an incredible app. It has not been occurring, everything's been fine as far as I can tell.
