### ISSUE TITLE
Wrong exercise (not row) shows up on timer after finished Bench

### ISSUE THREAD

**Issue by Krisztiaan** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#76]
**Did you look whether there is already an existing issue for your request?**

Yes

**Describe the bug**

After finishing the `Bench Press`, the timer prompts to prepare for `Incline Bench`, but the excercise order is actually `Bench -> Barbell Row -> Incline Bench`

**To Reproduce**
1. Go to a day with 3 excercises
2. Click through the first one, stop at last
3. Finish last rep
4. Observe last timer claiming the 3rd exercise (`Incline Bench`, in my case) as next

**Expected behavior**

`Barbell Row` should be shown as coming up instead

**Screenshots**

![nSuns excercise order bug](https://user-images.githubusercontent.com/4700811/60334250-56fe5580-999b-11e9-94e2-d0451b344887.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs
 - OS: iOS 13 Beta 1
 - App Version 1.11.1

**Comment by JonnyBeeGod** [comment]
Also the notification after timer countdown has finished is mentioning the third exercise instead of the second. Thanks for reporting

**Comment by JonnyBeeGod** [comment]
will be part of next release

**Comment by Krisztiaan** [comment]
Wow man, you are awesome
