### ISSUE TITLE
Audio notification next set

### ISSUE THREAD

**Issue by jaddel** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#79]
Hello,

since my friend also dose't get any audio notifications, i presume its not implemented. 

I would really love to see an audio notifications along the display notifications, so we could keep the display off to save battery and listening to music in the mean time.

**Comment by JonnyBeeGod** [comment]
The app follows standard iOS behavior by delivering a notification with sound if you 1. don’t have your iPhone muted and 2. your iPhone is locked the app is in the background so the Feature you are looking for should already been there. 😊( If Not then please let me know)

I agree however that it would be beneficial if the notification would also be delivered with sound if the device is unlocked and the app is in the foreground. Also a custom Sound would be cool 

Thanks for reporting!

**Comment by jaddel** [comment]
You're right, our phones were muted. 

> I agree however that it would be beneficial if the notification would also be delivered with sound if the device is unlocked and the app is in the foreground. Also a custom Sound would be cool

This would be perfect!
