### ISSUE TITLE
Progress not shown correctly after changing from 4day temp to 5day row temp.

### ISSUE THREAD

**Issue by jaddel** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#80]
I recently changed from the 4 day template to the 5 day row template. Now my Progress scheme is not updating anymore.

Please see the picture below.

![image](https://user-images.githubusercontent.com/46263124/62998213-200cd200-be6b-11e9-872e-8b3261bb1c13.png)

**Comment by JonnyBeeGod** [comment]
If you mean that the numbers are missing then that’s normal and it has nothing to do with the template. The numbers are not shown anymore if there are too many data points visible. To see the numbers again just pan to zoom on the graphs. If I misinterpreted the question please reopen

**Comment by jaddel** [comment]
ohh, i'm sorry it was as you said. But shouldn't the row also appear in the Training Progression when i switch to the 5day row template?
