### ISSUE TITLE
Timer not working for iOS 13

### ISSUE THREAD

**Issue by Joe-Goodall** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#81]
Since upgrading to iOS 13 the timer seems to be cleared when the app is in the background.

Steps to reproduce:

1. Start the rest timer.
2. Navigate away from the app - I opened the clock and started the stopwatch and let it count up to just over 30 seconds.
3. Navigate back to the app and the rest timer is now gone.

 - Device: iPhone Xs
 - OS: iOS 13.1
 - App Version: 1.11.2

**Comment by JonnyBeeGod** [comment]
I know, Apple has been taken it’s time reviewing my next update 😒 it will go live hopefully in the next days as soon as it’s approved with some cool stuff in it this time and should also fix the crashing timer issue. Cheers, Thanks for reporting

Von meinem iPad gesendet

**Comment by JonnyBeeGod** [comment]
Released the new app version yesterday. It would be great if you could report back if the problem still persists

**Comment by Joe-Goodall** [comment]
I can confirm the app updated overnight and the timer is now working as expected.

**Comment by jfclark35** [comment]
I have still been experiencing this issue, though only on t2 or accessory sets. T1 works ok.  The timer will disappear if I navigate away from the app or if my screen locks.  Sometimes the timer will also just not appear. 

 I do 4 day if it matters. 

Using IOS13 but I also noticed this happening before I updated from 12.
