### ISSUE TITLE
No notifications in iOS 13

### ISSUE THREAD

**Issue by samuelhoover** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#85]
I haven't seen an issue report about this bug yet surprisingly. Ever since I updated to the iOS 13 beta (iOS 13.1 public beta 2 I believe?) I've noticed that there are no notifications from the nSuns app. There isn't even an option for nSuns in the Notifications setting in Settings. There is the option to toggle notifications for the T1/2 sets and accessories within the app however.

**To Reproduce**
1. Open Settings > Notifications
2. No option for nSuns notifications
3. Open Settings > nSuns
4. No option for notifications
5. Open nSuns apps > Settings > Click "Permit notifications for Timer" > Opens nSuns in Settings

**Expected behavior**
Receive notifications after every T1/2 and accessory set. See options for nSuns in Settings > Notifications.

**Screenshots**
Opening Settings tab in nSuns app.
![IMG_2631](https://user-images.githubusercontent.com/56448170/66668121-76f01700-ec22-11e9-9c14-9222f59bc167.png)

Clicking on "Permit notifications for Timer" brings me here with no option to enable notifications for nSuns.
![IMG_2630](https://user-images.githubusercontent.com/56448170/66668120-76f01700-ec22-11e9-8ea3-8829e8d8165b.png)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.1 public beta 2 until present release of iOS 13.2 public beta 1
 - App Version: 1.13.0

**Comment by JonnyBeeGod** [comment]
iOS has been especially buggy with the new release, especially the beta versions. I pushed a new update to the store today with reworks around the notifications so maybe give it another shot. Please report back if the problem persists 

Von meinem iPhone gesendet

**Comment by samuelhoover** [comment]
Hi, sorry about the delayed response. Still experiencing the same issue (no notifications or option for notifications in iOS Notifications settings) and I'm now on iOS 13.2 public beta 4 and 1.13.0 for the app.

**Comment by JonnyBeeGod** [comment]
Yep thats a bug :) Thanks for reporting will provide a fix soon
