### ISSUE TITLE
UI issue when you swipe left for failed set 

### ISSUE THREAD

**Issue by ghost** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#86]
On the GA release of IOS 13.1.2 using the nSuns app, if you swipe left to mark a failed set, sometimes the set will disappear. You will have too back out of the exercises then back in to view it again. After a few attempts you can input the amount of sets you managed to do.  

To Reproduce

1) Open App
2) Start a new cycle
3) Select a exercise
4) Mark the first set as complete
5) Swipe left to mark the second set as failed, It may work the first time and let you input a number of failed sets. Try again and you will see the set disappear. 

Device: Iphone 7 
IOS 13.1.2
App Version 1.13.0

Thanks for all your hard work on the this app! 

Screenshot of set after is disappears:

![image](https://user-images.githubusercontent.com/52538048/66952199-287bb780-f02a-11e9-8a45-82163b2ad533.png)

**Comment by pegross** [comment]
Happens to me every time, preventing me to track any failed sets.
Great app btw., will def support every now and then :)

**Comment by JonnyBeeGod** [comment]
unfortunately the whole mechanic needs to change because apparently the swipe animations together with the keyboard animations are broken in iOS 13 :( am currently trying with beta testers whether tapping the textfield directly instead of swiping works as well

**Comment by ghost** [comment]
@JonnyBeeGod Sweet thanks!
