### ISSUE TITLE
Always-on screen

### ISSUE THREAD

**Issue by jabronismacker** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#87]
**Did you look whether there is already an existing issue for your request?**
Yes

**Describe the solution you'd like**
Please add an always-on screen

**Describe alternatives you've considered**
Changing iPhone display settings before and after working out

**Comment by JonnyBeeGod** [comment]
I like both ideas but please open a separate issue for each because they are completely unrelated :) I will consider this issue as the always on screen which is a quick win
