### ISSUE TITLE
Adjustable Workout days

### ISSUE THREAD

**Issue by JonnyBeeGod** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#9]

**Comment by aaron25mt** [comment]
Maybe just make this an option “Cycle Starts On” but default will follow the spreadsheet (Monday).

**Comment by JonnyBeeGod** [comment]
I think it needs to be more sophisticated because some people might like to workout the 4 day template in consecutive days instead of the Mon-Tue-Thu-Fr scheme.

**Comment by JonnyBeeGod** [comment]
Duplicate of #58
