### ISSUE TITLE
Bench press

### ISSUE THREAD

**Issue by brian57657** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#90]
**Describe the bug**
A clear and concise description of what the bug is. I’m doing the 5 day cycle and when I change my max for incline bench press it also changes for regular bench press. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - App Version (if known)

**Additional context**

**Comment by JonnyBeeGod** [comment]
This is intended behavior of this program and aligns nicely with the spreadsheet from the original program. If you feel the numbers are not right for you you can always change the percentages of incline bench in the template editor in the settings
