### ISSUE TITLE
Apple Watch app crashes on open

### ISSUE THREAD

**Issue by valmassoi** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#91]
**Did you look whether there is already an existing issue for your request?**
Yes

**Describe the bug**
App crashes instantly on the watch. I’ve tried reinstalling and different combinations of state of the app on the phone side (force quit, active cycle, ...) 

**To Reproduce**
1. Install on watch
2. Try to open

**Expected behavior**
Not crash

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro, series 4 watch
 - OS: iOS 13.3, WatchOS 6.1.1
 - App Version 1.13.1

**Additional context**

**Comment by JonnyBeeGod** [comment]
I have fixed this over the last week and the fix is included in my latest update which I submitted to Apple for review a couple of hours ago. Thanks for reporting!

**Comment by valmassoi** [comment]
Oh awesome! While I’m here... Any reason not to open source the project if you’re not charging anything? Either way thanks for the work.

**Comment by JonnyBeeGod** [comment]
> Oh awesome! While I’m here... Any reason not to open source the project if you’re not charging anything? Either way thanks for the work.

The thought has crossed my mind but until now I decided against it as this is my private little project I can work on at my own pace. I will however open source parts of it in the future. The last couple of weeks I have basically rewritten the timer as a SPM framework and this will be the first module that I will publish here
