### ISSUE TITLE
Timer Notifications for Accessory Exercises Fail to Create Notification

### ISSUE THREAD

**Issue by backdoc** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#92]
**Did you look whether there is already an existing issue for your request?**
Yes.

**Describe the bug**
Notifications are not being generated for accessory exercises.  Notifications for the T1/T2 are working correctly.

**To Reproduce**
Basically, to reproduce all you have to do is mark an accessory exercise and lock the phone and wait for the period of rest time (90 secs) to elapse.

**Expected behavior**
When I mark an accessory exercise complete, I expect it notify me on the phone and my Garmin watch, just like it does for the T1/T2 exercises.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device:
           XS Max
 - OS:
           13.3
 - App Version
           1.13.2

**Additional context**
None

**Comment by JonnyBeeGod** [comment]
correct, missed this when migrating to the new timer in the last update.

**Comment by JonnyBeeGod** [comment]
fixed in 1.14.0
