### ISSUE TITLE
Stuck in Initial Tutorial Flow, selecting template

### ISSUE THREAD

**Issue by DennyScott** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#94]
**Did you look whether there is already an existing issue for your request?**
Yes

**Describe the bug**
On two different Iphones, we opened the app (but both had used the app previous to the update where the 5-day row template was added).

We were taken immediately to fill out our new "Row TM". When we went into the page, we both used the "Calculate Training Max" button, where it auto fills the TM based on a 5 rep. When we did this method, it fills in the value, we clicked done, but the "done" in the template selection page would not fill in.

We eventually figured out that by going back into the row TM calculation, and manually writing the TM in will complete it.

**Expected behavior**
Autofilled Row TM should allow you to finish the template creation

**Screenshots**
Forgot to take screenshots. If it happens again, will update.

**Smartphone (please complete the following information):**
- IphoneXS
- Iphone 11Pro
Both on 13.3

**Comment by JonnyBeeGod** [comment]
Thanks for reporting I was getting reports but could not reproduce until now!

**Comment by JonnyBeeGod** [comment]
Fixed and shipped
