### ISSUE TITLE
Weight values for each side of the bar

### ISSUE THREAD

**Issue by zulu202** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#96]
First thing is first. This app is amazing, I love it. Thanks for putting time and effort into making this. 
The weights you get given is the total weight including bar. So when I’m in gym because I’m a tad slow with mathematics I have to use my calculator to minus 20kg from the total weight and then divide that total by 2. This gives me weight each side of the bar. Helps me get weights organised before I lift and I know exactly what’s each side next set. This might just be me who has this problem but just annoys me sometimes having to get the calculator out. Here is an example: bench - 70kg (25kg) 6 reps. Or something similar. Just a thought anyway. Thanks for reading

**Comment by JonnyBeeGod** [comment]
Thank you very much, really appreciate your feedback! I think this issue covers exactly what you want https://github.com/JonnyBeeGod/nSuns-5-3-1-iOS-issues/issues/3 if not let me know what it is missing. Cheers

**Comment by zulu202** [comment]
![DF9ED267-D63D-46B0-B3BE-6648BB07F034](https://user-images.githubusercontent.com/61242955/74961229-a4857200-5405-11ea-9990-5ecf4e2106fd.jpeg)
